### ISSUE TITLE
separate data from code

### ISSUE THREAD

**Issue by royaltm** [monstergdc/TurboWieszcz-Python#3]
Maybe the next step would be to have the verse data in separate files (e.g. JSON or YAML) to be able to re-use the code and provide alternative verse texts, perhaps in different languages.

**Comment by monstergdc** [comment]
I'd rather leave these as default (always present) and add XML/JSON reading capability. Already have the data in XML (Delphi/win version can do that already), but as newbie to Python I need to learn how to read from files :)

**Comment by monstergdc** [comment]
As ultimate blasphemy I have also "positive" verses prepeared:
	<dane>Jest tu tak fajnie</dane>
	<dane>Jest nadzwyczajnie</dane>
	<dane>Jest super hiper</dane>
	<dane>Jest zajefajnie</dane>
	<dane>Jest niebanalnie</dane>
	<dane>Jest superfajnie</dane>
	<dane>Jak w słodkiej pianie</dane>
	<dane>Nic się nie stanie</dane>

**Comment by monstergdc** [comment]
Worry not, XML reading almost working, neat :)

**Comment by royaltm** [comment]
wydaje mi się że najbardziej odpowiedni format do tego byłby YAML bo jest najbardziej przejrzysty dla niemaszyn https://pl.wikipedia.org/wiki/YAML Ułatwiłoby to też nieprogamistom dodawanie własnych wersji
XML is a mess - najlepiej dla świata byłoby jakby wszyscy zapomnieli o tym obskurnym formacie, co do JSON - polecam bardziej liberalną wersję: HJSON https://hjson.org

**Comment by royaltm** [comment]
blasphemy..... fuuuuuuuuuu!!!!11111

**Comment by royaltm** [comment]
sorry for using polish, sometimes I'm feeling I have limited control over which language I'm using at the moment :]

**Comment by monstergdc** [comment]
YAML/JSON - maybe later, 
btw. YAML - interesting, had no idea...
XML goes first, since I have some data ready and it'll be compatible with old Windows version.
